[package]
name = "plonk_wasm"
version = "0.1.0"
authors = ["opensource@o1labs.org"]
description = "WASM stubs for plonk proof systems"
repository = "https://github.com/MinaProtocol/mina"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "plonk_wasm"
crate-type = ["cdylib"]

################################# Dependencies ################################

[dependencies]
# Strictly enforcing 0.2.87.
# In the past, the library introduced breaking changes when updating the bugfix
# number, i.e it is not reliable to use semver. Also, the major version is 0,
# meaning it is not yet stable.
# See past breaking change: https://github.com/MinaProtocol/mina/issues/14253
wasm-bindgen = { version = "=0.2.87" }
console_error_panic_hook = { version = "0.1.6" }
web-sys = { version = "0.3.35", features = ["Window", "Document", "HtmlElement", "Text", "Node", "Element" ] }

once_cell = "1.10.0"
libc = { version = "0.2.0" }

# arkworks
ark-ff = { version = "0.3.0", features = ["parallel"] }
ark-serialize = "0.3.0"
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-poly = { version = "0.3.0", features = ["parallel"] }

# proof-systems
poly-commitment = { path = "../../../../../crypto/proof-systems/poly-commitment" }
groupmap = { path = "../../../../../crypto/proof-systems/groupmap" }
mina-curves = { path = "../../../../../crypto/proof-systems/curves" }
o1-utils = { path = "../../../../../crypto/proof-systems/utils" }
mina-poseidon = { path = "../../../../../crypto/proof-systems/poseidon" }
kimchi = { path = "../../../../../crypto/proof-systems/kimchi", features = ["wasm_types"] }

array-init = "2.0.0"
base64 = "0.13.0"
getrandom = { version = "0.2", features = ["js"] }
num-bigint = { version = "0.4.0" }
paste = "1.0.5"
rand = { version = "0.8.0" }
rayon = { version = "1" }
rmp-serde = "1.0.0"
sprs = { version = "0.11.0" }
spmc = {version = "0.3.0"}
serde = "1.0.130"
serde_json = "1.0"
serde_with = "2.0.1"
serde-wasm-bindgen = "0.4"
js-sys = "0.3"
# Version for proc-macro2 needs to be 1.0.60+ to be compatible with newer rust versions
# https://github.com/rust-lang/rust/issues/113152
proc-macro2 = { version = "=1.0.60", features=["default", "proc-macro"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[profile.release]
debug = true

[features]
nodejs = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
#wasm-opt = ["-O4", "--detect-features", "--enable-mutable-globals" ]
#wasm-opt = ["-O4", "--enable-mutable-globals"]

[build]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory", "-C", "link-arg=--no-check-features"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory", "-C", "link-arg=--no-check-features"]
