name: CI

on:
  pull_request:

env:
  # https://doc.rust-lang.org/cargo/reference/profiles.html#release
  RUSTFLAGS: -Coverflow-checks=y -Cdebug-assertions=y
  # https://doc.rust-lang.org/cargo/reference/profiles.html#incremental
  CARGO_INCREMENTAL: 1
  # https://nexte.st/book/pre-built-binaries.html#using-nextest-in-github-actions
  CARGO_TERM_COLOR: always

jobs:
  run_checks:
    strategy:
      matrix:
        rust_toolchain_version: ["nightly-2023-02-05"]

    runs-on: ubuntu-latest
    name: Run some basic checks and tests
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      # as action-rs does not seem to be maintained anymore, building from
      # scratch the environment using rustup
      - name: Setup Rust toolchain ${{ matrix.rust_toolchain_version }}
        run:
          |
            curl --proto '=https' --tlsv1.2 -sSf -o rustup-init \
            https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
            chmod +x ./rustup-init
            ./rustup-init -y --default-toolchain "${{ matrix.rust_toolchain_version }}" --profile default
            rm ./rustup-init
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      #
      # Coding guidelines
      #

      - name: Enforce formating
        run: |
          cd kimchi/wasm
          cargo fmt -- --check
